# frozen_string_literal: true

module Maintenance
  class T20261005backfillProcedureTagsFromLegacyTask < MaintenanceTasks::Task
    # Documentation: cette tâche rattache aux démarches les ProcedureTag qui
    # correspondent aux tags libres de l'ancienne colonne procedures.tags, via une
    # table de correspondance relue à la main. Elle ne fait qu'ajouter des tags,
    # et ne remet pas ceux que CreateProcedureTagsTask avait déjà rattachés.

    include RunnableOnDeployConcern
    include StatementsHelpersConcern

    run_on_first_deploy

    LEGACY_TAGS_PRESENT = "array_remove(procedures.tags, '') <> '{}'"

    # Les tags que CreateProcedureTagsTask (2024) a rattachés à chaque démarche existante
    # dont une valeur legacy portait exactement leur nom, casse ignorée.
    TAGS_LINKED_BY_CREATE_PROCEDURE_TAGS_TASK = [
      "Aap",
      "Accompagnement",
      "Action sociale",
      "Adeli",
      "Affectation",
      "Agrément",
      "Agriculture",
      "agroécologie",
      "Aide aux entreprises",
      "Aide financière",
      "Appel à manifestation d'intérêt",
      "AMI",
      "Animaux",
      "Appel à projets",
      "Association",
      "Auto-école",
      "Autorisation",
      "Autorisation d'exercer",
      "Bilan",
      "Biodiversité",
      "Candidature",
      "Cerfa",
      "Chasse",
      "Cinéma",
      "Cmg",
      "Collectivé territoriale",
      "Collège",
      "Convention",
      "Covid",
      "Culture",
      "Dérogation",
      "Diplôme",
      "Drone",
      "DSDEN",
      "Eau",
      "Ecoles",
      "Education",
      "Elections",
      "Energie",
      "Enseignant",
      "ENT",
      "Environnement",
      "Étrangers",
      "Formation",
      "FPRNM",
      "Funéraire",
      "Handicap",
      "Hygiène",
      "Industrie",
      "innovation",
      "Inscription",
      "Logement",
      "Lycée",
      "Manifestation",
      "Médicament",
      "Micro-crèche",
      "MODELE DS",
      "Numérique",
      "Permis",
      "Pompiers",
      "Préfecture",
      "Professionels de santé",
      "Recrutement",
      "Rh",
      "Santé",
      "Scolaire",
      "SDIS",
      "Sécurité",
      "Sécurité routière",
      "Sécurité sociale",
      "Séjour",
      "Service civique",
      "Subvention",
      "Supérieur",
      "Taxi",
      "Télétravail",
      "Tirs",
      "Transition écologique",
      "Transport",
      "Travail",
      "Université",
      "Urbanisme",
    ].freeze

    # Les tags que MAPPING vise et qui n'existent pas encore : la tâche les crée
    # à leur première attribution.
    NEW_TAGS = [
      "Alimentation",
      "Audiovisuel",
      "Concours",
      "Défense",
      "Enfance et jeunesse",
      "Famille",
      "Fiscalité",
      "Justice",
      "Langue française",
      "Mer",
      "Personnes âgées",
      "Petite enfance",
      "Police",
      "Prévention",
      "Risques majeurs",
      "Sport",
      "Tourisme",
    ].freeze

    # Valeur legacy (minuscules, sans espaces autour) → noms des tags à rattacher.
    MAPPING = {
      "#actionsociale" => ["Action sociale"],
      "#agrémentjep82" => ["Agrément"],
      "#bilan#cfppa#2023" => ["Bilan"],
      "#chambre agriculture grand est" => ["Agriculture"],
      "#derogation" => ["Dérogation"],
      "#diplome" => ["Diplôme"],
      "#diplôme" => ["Diplôme"],
      "#educationnationale" => ["Education"],
      "#emploipublic" => ["Recrutement"],
      "#habilitation" => ["Autorisation"],
      "#lyceepro" => ["Lycée"],
      "#lyceeprofessionnel" => ["Lycée"],
      "#police" => ["Police"],
      "#recrutement" => ["Recrutement"],
      "#rh" => ["Rh"],
      "#sport" => ["Sport"],
      "#vin" => ["Agriculture"],
      "#éducation" => ["Education"],
      "1000jours" => ["Petite enfance"],
      "14090*02" => ["Cerfa"],
      "2hspc" => ["Sport"],
      "2nde" => ["Lycée"],
      "3ea" => ["Scolaire"],
      "5g" => ["Numérique"],
      "7ème programme d'action nitrate" => ["Eau", "Agriculture"],
      "974" => ["Outre-mer"],
      "976" => ["Outre-mer"],
      "aah" => ["Handicap", "Aide financière"],
      "aap" => ["Aap"],
      "aap cada" => ["Appel à projets"],
      "aap cada 2024" => ["Appel à projets"],
      "aap deffinov -tiers lieux paca" => ["Appel à projets"],
      "aap deffinov tiers lieux 2023" => ["Appel à projets"],
      "aap-fjt-2024-haute-garonne" => ["Appel à projets", "Logement"],
      "aapaap" => ["Aap"],
      "aapth" => ["Appel à projets", "Handicap"],
      "aarc" => ["Agriculture"],
      "aasc" => ["Sécurité"],
      "abeille" => ["Animaux"],
      "accompagnement" => ["Accompagnement"],
      "accord prealable transport" => ["Transport", "Sécurité sociale"],
      "accès au droit" => ["Justice"],
      "acm" => ["Enfance et jeunesse"],
      "action social" => ["Action sociale"],
      "action sociale" => ["Action sociale"],
      "actionsociale" => ["Action sociale"],
      "activitephysique" => ["Sport"],
      "activité partielle" => ["Travail"],
      "activitéphysique" => ["Sport"],
      "actrice" => ["Culture"],
      "adcuefe" => ["Université", "Langue française"],
      "addiction" => ["Santé", "Prévention"],
      "adeli" => ["Adeli"],
      "adoption" => ["Famille"],
      "aefe" => ["Education"],
      "aeh" => ["Handicap", "Aide financière"],
      "affectation" => ["Affectation"],
      "agence de l'eau" => ["Eau"],
      "agence de l'innovation de défense" => ["innovation", "Défense"],
      "agents_contractuels" => ["Rh"],
      "agents_publics" => ["Rh"],
      "agrement" => ["Agrément"],
      "agricole" => ["Agriculture"],
      "agriculteur" => ["Agriculture"],
      "agriculteurs" => ["Agriculture"],
      "agriculture" => ["Agriculture"],
      "agrimer" => ["Agriculture"],
      "agro-alimentaire" => ["Alimentation"],
      "agroecologie" => ["agroécologie"],
      "agroforesterie" => ["agroécologie"],
      "agroécologie" => ["agroécologie"],
      "agrégation" => ["Enseignant", "Concours"],
      "agrément" => ["Agrément"],
      "agrément jep" => ["Agrément", "Enfance et jeunesse"],
      "aidants" => ["Action sociale"],
      "aide a la continuite territoriale" => ["Aide financière"],
      "aide alimentaire" => ["Action sociale"],
      "aide aux entreprises" => ["Aide aux entreprises"],
      "aide financière" => ["Aide financière"],
      "aide sociale" => ["Action sociale"],
      "aides aux entreprises" => ["Aide aux entreprises"],
      "algorithme" => ["Numérique"],
      "alimentaire" => ["Alimentation"],
      "alimentation" => ["Alimentation"],
      "alliances locales des solidarites" => ["Action sociale"],
      "allocation" => ["Aide financière"],
      "allocation chômage bspp" => ["Travail"],
      "allocations" => ["Aide financière"],
      "alternance" => ["Formation"],
      "alternant" => ["Formation"],
      "ambulance" => ["Transport", "Santé"],
      "ambulancier" => ["Transport"],
      "ambulatoire" => ["Santé"],
      "ami" => ["AMI"],
      "amicale" => ["Association"],
      "anact" => ["Travail"],
      "anct" => ["Collectivé territoriale"],
      "animal" => ["Animaux"],
      "animaux" => ["Animaux"],
      "animaux disparus" => ["Animaux"],
      "antigaspillage" => ["Environnement"],
      "antilles" => ["Outre-mer"],
      "anxiété" => ["Santé"],
      "api" => ["Numérique"],
      "appel a projets" => ["Appel à projets"],
      "appel à projets" => ["Appel à projets"],
      "appel à projets\nagricole" => ["Appel à projets", "Agriculture"],
      "apprenti" => ["Formation"],
      "apprentis" => ["Formation"],
      "apprentisage" => ["Formation"],
      "apprentissage" => ["Formation"],
      "aptitude conduite" => ["Permis"],
      "arboviroses" => ["Santé"],
      "arbre" => ["Environnement"],
      "archives" => ["Archives"],
      "arcom" => ["Audiovisuel"],
      "armateur" => ["Mer"],
      "armes" => ["Sécurité"],
      "armée" => ["Défense"],
      "armée de l'air et de l'espace" => ["Défense"],
      "armées" => ["Défense"],
      "arretdetravail" => ["Travail"],
      "arrosage" => ["Eau"],
      "ars" => ["Santé"],
      "ars de corse" => ["Santé"],
      "ars nouvelle-aquitaine" => ["Santé"],
      "artiste" => ["Culture"],
      "asile" => ["Étrangers"],
      "asll" => ["Logement"],
      "assainissement" => ["Eau"],
      "associatif" => ["Association"],
      "associatifs" => ["Association"],
      "association" => ["Association"],
      "association reconnue d'utilité publique" => ["Association"],
      "associations" => ["Association"],
      "associations reconnues d'utilité publique" => ["Association"],
      "assurance maladie" => ["Sécurité sociale"],
      "ate temporaire lauréat evc 2021" => ["Autorisation d'exercer", "Professionels de santé"],
      "attestation de diplome" => ["Diplôme"],
      "audioprothésiste" => ["Professionels de santé"],
      "aujeszky" => ["Animaux"],
      "autisme" => ["Handicap"],
      "auto-ecole" => ["Auto-école"],
      "auto-école" => ["Auto-école"],
      "autorisation" => ["Autorisation"],
      "autorisation d'exercer" => ["Autorisation d'exercer"],
      "autorisation de cumul" => ["Autorisation"],
      "autorisation générale" => ["Autorisation"],
      "autorisations" => ["Autorisation"],
      "autoroute" => ["Transport"],
      "avdl" => ["Logement"],
      "aviaire" => ["Animaux"],
      "avicole" => ["Animaux"],
      "baccalauréat" => ["Diplôme"],
      "bafd" => ["Diplôme", "Enfance et jeunesse"],
      "bailleur" => ["Logement"],
      "bailleurs" => ["Logement"],
      "bailleurs sociaux" => ["Logement"],
      "banane" => ["Agriculture"],
      "barnier" => ["FPRNM"],
      "bcae" => ["Agriculture"],
      "beges" => ["Bilan", "Environnement"],
      "bilan" => ["Bilan"],
      "bilan des émissions de gaz à effet de serre" => ["Bilan", "Environnement"],
      "biodiversité" => ["Biodiversité"],
      "biogaz" => ["Energie"],
      "biomasse" => ["Energie"],
      "biométhane" => ["Energie"],
      "biotopes" => ["Biodiversité"],
      "bitd" => ["Industrie", "Défense"],
      "bnssa" => ["Diplôme"],
      "bop 104" => ["Étrangers"],
      "bop104" => ["Étrangers"],
      "bop104action12" => ["Étrangers"],
      "bourse" => ["Aide financière"],
      "bovin" => ["Animaux"],
      "brucellose" => ["Animaux"],
      "bruit" => ["Environnement"],
      "bts" => ["Supérieur"],
      "btsa" => ["Supérieur"],
      "bénéficiaire de la protection internationale" => ["Étrangers"],
      "caaecep" => ["Association", "Agrément"],
      "cabinets médicaux" => ["Santé"],
      "caf" => ["Sécurité sociale"],
      "caferuis" => ["Diplôme"],
      "campus france" => ["Supérieur"],
      "cancers" => ["Santé"],
      "candidature" => ["Candidature"],
      "candidatures" => ["Candidature"],
      "cantine" => ["Scolaire"],
      "capacité de transport" => ["Transport"],
      "capes" => ["Enseignant"],
      "caprin" => ["Animaux"],
      "captage" => ["Eau"],
      "cardie" => ["Education", "innovation"],
      "casdar" => ["Agriculture"],
      "casier judiciaire" => ["Justice"],
      "cch" => ["Logement"],
      "cci usagers indeminisation conciliation santé" => ["Santé"],
      "cdac" => ["Urbanisme"],
      "cdd spv" => ["Pompiers", "Recrutement"],
      "cerfa" => ["Cerfa"],
      "cerfa n°12156*05" => ["Cerfa"],
      "certificatimmatriculation" => ["Transport"],
      "cfa" => ["Formation"],
      "cfppa" => ["Personnes âgées"],
      "charte informatique" => ["Numérique"],
      "chasse" => ["Chasse"],
      "chien" => ["Animaux"],
      "chirurgie" => ["Santé"],
      "chlordécone" => ["Environnement"],
      "choisirleservicepublic" => ["Recrutement"],
      "chu" => ["Santé"],
      "chômage" => ["Travail"],
      "cigogne" => ["Animaux"],
      "cii" => ["innovation", "Fiscalité"],
      "cinéma" => ["Cinéma"],
      "cipan" => ["Agriculture", "Environnement"],
      "circuit_court" => ["Agriculture"],
      "civilsdeladéfense" => ["Défense"],
      "clact" => ["Travail"],
      "climat" => ["Transition écologique"],
      "cloud" => ["Numérique"],
      "cmg" => ["Cmg"],
      "cned" => ["Education"],
      "cnrsanté" => ["Santé"],
      "co-parent" => ["Famille"],
      "code de la construction et de l'habitation" => ["Logement"],
      "code de la route" => ["Sécurité routière"],
      "codedelaroute2rm" => ["Sécurité routière"],
      "collectivites" => ["Collectivé territoriale"],
      "collectivité" => ["Collectivé territoriale"],
      "collectivités" => ["Collectivé territoriale"],
      "collectivé territoriale" => ["Collectivé territoriale"],
      "college" => ["Collège"],
      "collège" => ["Collège"],
      "collèges" => ["Collège"],
      "colos" => ["Enfance et jeunesse"],
      "communauté360" => ["Handicap"],
      "communautés360" => ["Handicap"],
      "communes" => ["Collectivé territoriale"],
      "communes_rurales" => ["Collectivé territoriale"],
      "commémoration" => ["Histoire"],
      "concert" => ["Culture"],
      "concerts" => ["Culture"],
      "concours" => ["Concours"],
      "concours général agricole" => ["Agriculture", "Concours"],
      "conditions-de-travail" => ["Travail"],
      "conférence des financeurs" => ["Personnes âgées"],
      "congres" => ["Manifestation"],
      "congésdemaladie" => ["Travail"],
      "conseildépartemental" => ["Collectivé territoriale"],
      "contester refus etias" => ["Étrangers"],
      "contractuels" => ["Rh"],
      "contrôle de légalité" => ["Collectivé territoriale"],
      "convention" => ["Convention"],
      "coquillages" => ["Mer"],
      "corbeau" => ["Animaux"],
      "corneille" => ["Animaux"],
      "corvidés" => ["Animaux"],
      "cours d'eau" => ["Eau"],
      "coursd'eau" => ["Eau"],
      "coursdeau" => ["Eau"],
      "couverts d'interculture" => ["Agriculture"],
      "covid" => ["Covid"],
      "covoiturage" => ["Transport"],
      "cpam" => ["Sécurité sociale"],
      "cpam78" => ["Sécurité sociale"],
      "cpf" => ["Formation"],
      "cpge" => ["Supérieur"],
      "crack" => ["Santé"],
      "crpe" => ["Recrutement", "Enseignant"],
      "crsa" => ["Santé"],
      "crsa/csdu" => ["Santé"],
      "crèche" => ["Petite enfance"],
      "crémation" => ["Funéraire"],
      "cse" => ["Travail"],
      "cssr" => ["Sécurité routière"],
      "culture" => ["Culture"],
      "culturelle" => ["Culture"],
      "cuma" => ["Agriculture"],
      "cumul d'activité" => ["Rh"],
      "cyber" => ["Numérique"],
      "cyberdéfense" => ["Défense"],
      "cybersécurité" => ["Numérique", "Sécurité"],
      "céréales" => ["Agriculture"],
      "d'eau" => ["Eau"],
      "d'engraissement" => ["Agriculture"],
      "d'exploiter" => ["Autorisation"],
      "d'urbanisme" => ["Urbanisme"],
      "dab+" => ["Audiovisuel"],
      "daho" => ["Logement"],
      "dalf" => ["Langue française"],
      "dalo" => ["Logement"],
      "dane" => ["Numérique", "Education"],
      "data governance act" => ["Numérique"],
      "de candidature" => ["Candidature"],
      "deaes" => ["Diplôme"],
      "deaf" => ["Diplôme"],
      "deap" => ["Diplôme"],
      "deas" => ["Diplôme"],
      "deass" => ["Diplôme"],
      "decrochage" => ["Scolaire"],
      "deeje" => ["Diplôme"],
      "deffinov-paca" => ["Appel à projets"],
      "deffinov-paca-2023" => ["Appel à projets"],
      "deis" => ["Diplôme"],
      "delf" => ["Langue française"],
      "demande d'agrément" => ["Agrément"],
      "demande d'autorisation" => ["Autorisation"],
      "demande de financement" => ["Aide financière"],
      "demande d’autorisation temporaire d’exercice pour padhue" => ["Autorisation d'exercer", "Professionels de santé"],
      "dematads" => ["Urbanisme"],
      "demf" => ["Diplôme"],
      "demi-pension" => ["Scolaire"],
      "denrees" => ["Alimentation"],
      "detisf" => ["Diplôme"],
      "detr" => ["Subvention", "Collectivé territoriale"],
      "detr-dsil" => ["Subvention", "Collectivé territoriale"],
      "detr/dsil" => ["Subvention"],
      "dgafp" => ["Rh"],
      "dgampa" => ["Mer"],
      "dger" => ["Education"],
      "dgf" => ["Collectivé territoriale"],
      "dgpn" => ["Police"],
      "dina cuma" => ["Agriculture"],
      "dinum" => ["Numérique"],
      "diplome" => ["Diplôme"],
      "diplomes" => ["Diplôme"],
      "diplôme" => ["Diplôme"],
      "diplôme universitaire" => ["Diplôme", "Université"],
      "diplômes" => ["Diplôme"],
      "dirm" => ["Mer"],
      "dispositif jeune" => ["Enfance et jeunesse"],
      "dispositif médical" => ["Santé"],
      "doctorant" => ["Supérieur"],
      "dom-tom" => ["Outre-mer"],
      "dpv" => ["Subvention"],
      "draaf" => ["Agriculture"],
      "drac" => ["Culture"],
      "drajes" => ["Enfance et jeunesse"],
      "drane" => ["Numérique", "Education"],
      "drihl" => ["Logement"],
      "drogues" => ["Santé", "Prévention"],
      "droitssociaux" => ["Action sociale"],
      "drom" => ["Outre-mer"],
      "drom-com" => ["Outre-mer"],
      "drone" => ["Drone"],
      "ds" => ["MODELE DS"],
      "dsden" => ["DSDEN"],
      "dsec" => ["Subvention"],
      "dsi" => ["Numérique"],
      "dsid" => ["Subvention", "Collectivé territoriale"],
      "dsil" => ["Subvention", "Collectivé territoriale"],
      "du numérique" => ["Numérique"],
      "duef" => ["Université", "Langue française"],
      "dys" => ["Handicap"],
      "déchets" => ["Environnement"],
      "déchetterie" => ["Environnement"],
      "défense" => ["Défense"],
      "délinquance" => ["Sécurité"],
      "dématérialisation" => ["Numérique"],
      "déminage" => ["Sécurité"],
      "démocratie sanitaire" => ["Santé"],
      "dépistagedescancers" => ["Santé"],
      "dépistages" => ["Santé", "Prévention"],
      "dépollution" => ["Environnement"],
      "dérogation" => ["Dérogation"],
      "dérogation pl" => ["Dérogation", "Transport"],
      "e-santé" => ["Santé", "Numérique"],
      "eac" => ["Culture", "Education"],
      "eau" => ["Eau"],
      "eaux" => ["Eau"],
      "eaux de" => ["Eau"],
      "eaux-grises" => ["Eau"],
      "ecole" => ["Ecoles"],
      "ecole ouverte" => ["Scolaire"],
      "ecoles" => ["Ecoles"],
      "ecologie" => ["Environnement"],
      "ecophyto" => ["Agriculture", "Environnement"],
      "ecosystèmes" => ["Biodiversité"],
      "education" => ["Education"],
      "education;civique" => ["Education"],
      "educfi" => ["Education"],
      "educnat" => ["Education"],
      "eeca" => ["Auto-école"],
      "eedd" => ["Environnement", "Education"],
      "effluents agricoles" => ["Agriculture"],
      "effluents d'élevage" => ["Agriculture"],
      "egalim" => ["Agriculture"],
      "egalim2" => ["Agriculture"],
      "ehpad" => ["Personnes âgées"],
      "elections" => ["Elections"],
      "electricité" => ["Energie"],
      "elevage" => ["Agriculture", "Animaux"],
      "eleve" => ["Scolaire"],
      "embâcles" => ["Eau"],
      "emlpoi" => ["Travail"],
      "emménagement" => ["Logement"],
      "emploi" => ["Travail"],
      "emploifranc" => ["Travail"],
      "emploifrancs" => ["Travail"],
      "emplois" => ["Travail"],
      "employeur" => ["Travail"],
      "en famille" => ["Scolaire"],
      "energie" => ["Energie"],
      "enfance" => ["Enfance et jeunesse"],
      "enfants" => ["Enfance et jeunesse"],
      "enm" => ["Justice"],
      "enr" => ["Energie"],
      "ensa" => ["Supérieur"],
      "enseignant" => ["Enseignant"],
      "enseignement" => ["Education"],
      "enseignement agricole" => ["Education", "Agriculture"],
      "enseignement artistique" => ["Culture", "Education"],
      "enseignement privé" => ["Education"],
      "enseignements artistiques" => ["Culture", "Education"],
      "ent" => ["ENT"],
      "environnement" => ["Environnement"],
      "envoi (export) de végétaux de la guadeloupe vers la france et l'union européenne" => ["Agriculture"],
      "eolien" => ["Energie"],
      "epci" => ["Collectivé territoriale"],
      "eple" => ["Scolaire"],
      "eplefpa" => ["Education", "Agriculture"],
      "epreuve_chiens_chasse" => ["Chasse", "Animaux"],
      "ergothérapeute" => ["Professionels de santé"],
      "esanté" => ["Santé", "Numérique"],
      "esms" => ["Action sociale"],
      "esod" => ["Animaux"],
      "espace vert" => ["Environnement"],
      "espacessanstabac" => ["Santé"],
      "estiprev" => ["Agriculture"],
      "etablissements de santé" => ["Santé"],
      "etablissements sanitaires" => ["Santé"],
      "etalab" => ["Numérique"],
      "etg" => ["Permis"],
      "etias" => ["Étrangers"],
      "etrangers" => ["Étrangers"],
      "etudiant" => ["Supérieur"],
      "etudiants" => ["Supérieur"],
      "eurotunnel" => ["Transport"],
      "evaluation environnementale" => ["Environnement"],
      "evc 2024" => ["Professionels de santé"],
      "evènement" => ["Manifestation"],
      "exception_handicap" => ["Handicap"],
      "famille" => ["Scolaire"],
      "fatesat" => ["Handicap"],
      "faucardage" => ["Eau"],
      "faune" => ["Biodiversité"],
      "fctva" => ["Collectivé territoriale"],
      "fdva" => ["Association"],
      "ferroviaire" => ["Transport"],
      "ferry" => ["Transport"],
      "festival" => ["Manifestation", "Culture"],
      "fipd" => ["Sécurité", "Prévention"],
      "fiscalité" => ["Fiscalité"],
      "flammeolympique" => ["Sport"],
      "fle" => ["Langue française"],
      "flore" => ["Biodiversité"],
      "fnadt" => ["Subvention"],
      "fnavdl" => ["Logement"],
      "foire" => ["Manifestation"],
      "foiredeparis" => ["Manifestation"],
      "fonctionnaires" => ["Rh"],
      "fonctionpublique" => ["Rh"],
      "fonds barnier" => ["FPRNM"],
      "fonds vert" => ["Transition écologique", "Environnement"],
      "fonds-vert" => ["Transition écologique", "Environnement"],
      "fondsdeluttecontrelesaddictions" => ["Santé"],
      "fondsurgence" => ["Aide financière"],
      "fondsvert" => ["Transition écologique", "Environnement"],
      "fonjep" => ["Subvention", "Association"],
      "foret" => ["Environnement"],
      "formateur" => ["Formation"],
      "formation" => ["Formation"],
      "formation_hygiène" => ["Formation", "Hygiène"],
      "formationaction" => ["Formation"],
      "forêt" => ["Environnement"],
      "forêtdomaniale" => ["Environnement"],
      "forêts" => ["Environnement"],
      "fouine" => ["Animaux"],
      "fprnm" => ["FPRNM"],
      "fr alert" => ["Sécurité"],
      "frafu" => ["Urbanisme"],
      "france_nation_verte" => ["Transition écologique"],
      "france_numérique_ensemble" => ["Numérique"],
      "franceagrimer" => ["Agriculture"],
      "francecompétence" => ["Formation"],
      "francenationverte" => ["Transition écologique"],
      "francophonie" => ["Langue française"],
      "frenchtech" => ["innovation", "Numérique"],
      "fumier" => ["Agriculture"],
      "funeraire" => ["Funéraire"],
      "funéraire" => ["Funéraire"],
      "futuna" => ["Outre-mer"],
      "fête" => ["Manifestation"],
      "fêtes foraines" => ["Manifestation"],
      "gaec" => ["Agriculture"],
      "gar" => ["Numérique"],
      "gendarmerie" => ["Police"],
      "ges" => ["Environnement"],
      "giee" => ["Agriculture", "agroécologie"],
      "gmnf" => ["Lycée"],
      "greta" => ["Formation"],
      "groupement de coopération sanitaire" => ["Santé"],
      "guadeloupe" => ["Outre-mer"],
      "guichet unique haies alignement arbres eure projet travaux signalement agriculteurs agriculture environnement paysage" => ["Agriculture", "Environnement"],
      "guid'asso" => ["Association"],
      "guid'asso 61" => ["Association"],
      "guid'asso orne" => ["Association"],
      "guidasso" => ["Association"],
      "guyane" => ["Outre-mer"],
      "habilitation" => ["Autorisation"],
      "habitat indigne" => ["Logement"],
      "habitation" => ["Logement"],
      "hackathon" => ["innovation"],
      "had" => ["Santé"],
      "haie" => ["Biodiversité"],
      "haies" => ["Biodiversité"],
      "handicap" => ["Handicap"],
      "handicap parking" => ["Handicap"],
      "health data hub" => ["Santé"],
      "histoire" => ["Histoire"],
      "hopital" => ["Santé"],
      "horticulture" => ["Agriculture"],
      "huda" => ["Étrangers"],
      "huiles usagees" => ["Environnement"],
      "huiles usees" => ["Environnement"],
      "hygiene alimentaire" => ["Hygiène"],
      "hygiène" => ["Hygiène"],
      "hygiène_alimentaire" => ["Hygiène"],
      "ia générative" => ["Numérique"],
      "iahp" => ["Animaux"],
      "icpe" => ["Environnement"],
      "ief" => ["Scolaire"],
      "ihedn" => ["Défense"],
      "inao" => ["Agriculture"],
      "incubateur" => ["innovation"],
      "industrie" => ["Industrie"],
      "infirmier" => ["Professionels de santé"],
      "infirmière" => ["Professionels de santé"],
      "informatique" => ["Numérique"],
      "inhumation" => ["Funéraire"],
      "innovation" => ["innovation"],
      "innovation publique" => ["innovation"],
      "innovationterritoriale" => ["innovation"],
      "inondation" => ["Risques majeurs"],
      "inscription" => ["Inscription"],
      "instruction_famille" => ["Scolaire"],
      "intelligenceartificielle" => ["Numérique"],
      "interculture" => ["Agriculture"],
      "internat" => ["Scolaire"],
      "interoperabilité" => ["Numérique"],
      "interventionprecoce" => ["Prévention"],
      "intradef" => ["Défense"],
      "iode" => ["Santé"],
      "iprp santé sécurité code du travail" => ["Travail"],
      "irrigation" => ["Agriculture", "Eau"],
      "irrigation prélèvement" => ["Eau"],
      "isft" => ["Logement"],
      "jeune" => ["Enfance et jeunesse"],
      "jeunes" => ["Enfance et jeunesse"],
      "jeunes espoirs sportifs" => ["Sport"],
      "jeunesse" => ["Enfance et jeunesse"],
      "jnqa" => ["Environnement"],
      "jobdating" => ["Recrutement"],
      "jop" => ["Sport"],
      "journée nationale de la qualité de l'air" => ["Environnement"],
      "journée nationale de la résilience-appel à projets 2023" => ["Appel à projets", "Risques majeurs"],
      "l'eaud'ici" => ["Eau"],
      "la pauvrete" => ["Action sociale"],
      "la pauvreté" => ["Action sociale"],
      "la réunion" => ["Outre-mer"],
      "laboratoires d'innovation" => ["innovation"],
      "ladom" => ["Outre-mer"],
      "lapin" => ["Animaux"],
      "legta" => ["Lycée"],
      "lhi" => ["Logement"],
      "lien social" => ["Action sociale"],
      "lieutenant de louveterie" => ["Chasse"],
      "lieuxdesantesanstabac" => ["Santé"],
      "lisier" => ["Agriculture"],
      "littoral" => ["Mer"],
      "locataire" => ["Logement"],
      "locatif" => ["Logement"],
      "locative" => ["Logement"],
      "logement" => ["Logement"],
      "logement communal" => ["Logement"],
      "logement-communal" => ["Logement"],
      "loup" => ["Animaux"],
      "loups" => ["Animaux"],
      "louveterie" => ["Chasse"],
      "louvetier" => ["Chasse"],
      "lycee" => ["Lycée"],
      "lycée" => ["Lycée"],
      "lycéen" => ["Lycée"],
      "lycées" => ["Lycée"],
      "l’agence régionale de santé provence-alpes-côte d'azur (ci-après ars) procède à un traitement de données à caractère personnel pour permettre la gestion et le suivi des agréments des transporteurs sanitaires et des autorisations de véhicules affectés aux transports sanitaires terrestres conformément aux dispositions des articles l.6312-2 et suivants et r.6312-1 et suivants du code de la santé publique. ce traitement relève de l’exercice de l’autorité publique à laquelle l’ars, en sa qualité de responsable de traitement, est investie en application de l’article 6.1.e du règlement général sur la protection des données (rgpd) du 27 avril 2016. les données enregistrées sont conservées jusqu’au retrait de l’agrément de transport sanitaire et ne peuvent être communiquées qu’aux destinataires suivants: personnels du service régional des transports sanitaires de l’ars et personnels habilités de l’assurance maladie.  conformément au rgpd et à la loi n° 78-du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés, vous disposez d’un droit d’accès, de rectification, de limitation et d’opposition aux données vous concernant.  vous pouvez exercer ces droits en adressant un courrier signé accompagné de la copie d’un justificatif d’identité au délégué à la protection des données de l’ars à l’adresse suivante : madame la déléguée à la protection des données de l’ars paca, 132 boulevard de paris - 13002 marseille ou par courriel : ars-paca-dpo@ars.sante.fr.  vous disposez d’un droit d'introduire une réclamation auprès de la commission nationale de l’informatique et des libertés, si vous considérez que le traitement de données à caractère personnel vous concernant constitue une violation du rgpd et de la loi informatique et libertés." => ["Santé"],
      "magistrature" => ["Justice"],
      "mairie" => ["Collectivé territoriale"],
      "maisonsportsante" => ["Santé", "Sport"],
      "maisonsportsanté" => ["Santé", "Sport"],
      "maisonsportsanté2022" => ["Sport"],
      "maisonsportsanté2024" => ["Santé", "Sport"],
      "maladeschroniques" => ["Santé"],
      "maladie hémorragique épizootique" => ["Animaux"],
      "maltraitance" => ["Action sociale"],
      "mandataire judiciaire à la protection des majeurs" => ["Action sociale", "Justice"],
      "manifestation" => ["Manifestation"],
      "manifestation sportive" => ["Manifestation", "Sport"],
      "manifestations" => ["Manifestation"],
      "maraîchage" => ["Agriculture"],
      "maraîcher" => ["Agriculture"],
      "mariage" => ["Famille"],
      "marin" => ["Mer"],
      "marine nationale" => ["Défense"],
      "marines" => ["Mer"],
      "marins" => ["Mer"],
      "maritime" => ["Mer"],
      "mariés" => ["Famille"],
      "martinique" => ["Outre-mer"],
      "master" => ["Diplôme", "Supérieur"],
      "mastère" => ["Diplôme"],
      "mayotte" => ["Outre-mer"],
      "medecin" => ["Professionels de santé", "Santé"],
      "mer" => ["Mer"],
      "methanisation" => ["Energie"],
      "mhe" => ["Animaux"],
      "micro-crèche" => ["Micro-crèche", "Petite enfance"],
      "micro-folies" => ["Culture"],
      "microfolies" => ["Culture"],
      "mildeca" => ["Santé", "Prévention"],
      "militaire" => ["Défense"],
      "minarm" => ["Défense"],
      "minimis" => ["Aide aux entreprises"],
      "misen" => ["Eau", "Environnement"],
      "mjpm" => ["Action sociale"],
      "mlds" => ["Scolaire"],
      "mmpt" => ["Alimentation"],
      "mobilité professionnelle" => ["Rh"],
      "mobilités" => ["Transport"],
      "modele" => ["MODELE DS"],
      "modele ds" => ["MODELE DS"],
      "moins de 16 ans" => ["Enfance et jeunesse"],
      "monuments" => ["Patrimoine"],
      "moodle" => ["Numérique"],
      "moustique" => ["Santé"],
      "msa" => ["Sécurité sociale"],
      "mss2024" => ["Santé"],
      "musique" => ["Culture"],
      "médecin" => ["Professionels de santé", "Santé"],
      "médecine" => ["Santé"],
      "médecins" => ["Professionels de santé", "Santé"],
      "médecins agréés" => ["Professionels de santé", "Agrément", "Santé"],
      "médical" => ["Santé"],
      "médicament" => ["Médicament"],
      "médico-social" => ["Action sociale"],
      "mérule" => ["Logement"],
      "naissance" => ["Famille"],
      "natura" => ["Environnement"],
      "naturalisation" => ["Étrangers"],
      "nature" => ["Environnement"],
      "naval" => ["Mer"],
      "navigation fluviale" => ["Transport"],
      "navigation_fluviale" => ["Transport"],
      "navire" => ["Mer"],
      "neph" => ["Permis"],
      "nettoyage des plages" => ["Environnement", "Mer"],
      "nitrate" => ["Environnement"],
      "nitrates" => ["Environnement"],
      "njpf" => ["Lycée"],
      "non lauréats des evc 2023" => ["Autorisation d'exercer"],
      "non-recours" => ["Action sociale"],
      "nonrecours" => ["Action sociale"],
      "nouméa" => ["Outre-mer"],
      "nouvelle-calédonie" => ["Outre-mer"],
      "nuisances sonores" => ["Environnement"],
      "nuisible" => ["Animaux"],
      "nuisibles" => ["Animaux"],
      "numerique" => ["Numérique"],
      "numérique" => ["Numérique"],
      "occupation du domaine public" => ["Autorisation"],
      "océan" => ["Mer"],
      "oepre" => ["Education", "Langue française"],
      "offredesoins" => ["Santé"],
      "ofpra" => ["Étrangers"],
      "olympiadeculturelle" => ["Culture"],
      "oléoprotéagineux" => ["Agriculture"],
      "omedit" => ["Médicament"],
      "onf" => ["Environnement"],
      "oniam" => ["Santé"],
      "opco" => ["Formation"],
      "opendata" => ["Numérique"],
      "opensource" => ["Numérique"],
      "orsec" => ["Sécurité"],
      "orthophoniste" => ["Professionels de santé"],
      "ouragan béryl fsom aide entreprises" => ["Aide aux entreprises", "Outre-mer"],
      "outre-mer" => ["Outre-mer"],
      "ovin" => ["Animaux"],
      "pacage" => ["Agriculture"],
      "pacs" => ["Famille"],
      "pacsés" => ["Famille"],
      "pactehaie" => ["Biodiversité"],
      "padhue" => ["Professionels de santé", "Autorisation d'exercer"],
      "paec" => ["Agriculture"],
      "paiement subventions dordogne" => ["Subvention"],
      "palmipèdes" => ["Animaux"],
      "palombe" => ["Chasse"],
      "papi" => ["Risques majeurs"],
      "paralympiques" => ["Sport"],
      "paramédical" => ["Professionels de santé"],
      "paramédicale" => ["Professionels de santé"],
      "parc naturel marin du golfe du lion" => ["Environnement", "Mer"],
      "parcoursup" => ["Supérieur"],
      "parentalité" => ["Famille"],
      "parents" => ["Famille"],
      "partenariat en santé" => ["Santé"],
      "passeport mobilitã© ã©tudiant" => ["Supérieur"],
      "pastoralisme" => ["Agriculture"],
      "patient" => ["Santé"],
      "patrimoine" => ["Patrimoine"],
      "pauvreté" => ["Action sociale"],
      "pdalhpd" => ["Logement"],
      "pdasr" => ["Sécurité routière"],
      "pdasr2024" => ["Sécurité routière"],
      "pdasr2024yonne89" => ["Sécurité routière"],
      "pdesi" => ["Sport"],
      "pedt" => ["Education"],
      "perdrix" => ["Chasse"],
      "permis" => ["Permis"],
      "personne_agée" => ["Personnes âgées"],
      "personnes handicapées vieillissantes" => ["Handicap"],
      "personnes-âgées" => ["Personnes âgées"],
      "perte d'autonomie" => ["Personnes âgées"],
      "perte diplômes d'état" => ["Diplôme"],
      "perturbateurs-endocriniens" => ["Santé"],
      "peste" => ["Animaux"],
      "petiteenfance" => ["Petite enfance"],
      "pfas" => ["Environnement"],
      "pfmp" => ["Formation"],
      "pfr handicap" => ["Handicap"],
      "pgsse" => ["Eau"],
      "pharmaceutique" => ["Médicament"],
      "pharmacie" => ["Médicament"],
      "photovolaïque" => ["Energie"],
      "photovoltaique" => ["Energie"],
      "photovoltaïque" => ["Energie"],
      "phyto" => ["Agriculture"],
      "phytosanitaire" => ["Agriculture"],
      "pigeon" => ["Animaux"],
      "pjj" => ["Justice"],
      "pl de plus de 7.5t" => ["Transport"],
      "plai" => ["Logement"],
      "plan de vidéoprotection" => ["Sécurité"],
      "planificationecologique" => ["Transition écologique"],
      "plans d'eau" => ["Eau"],
      "plat'au" => ["Urbanisme"],
      "plateforme de repit" => ["Action sociale"],
      "pmr" => ["Handicap"],
      "pndar" => ["Agriculture"],
      "pnmgl" => ["Mer"],
      "pole énergie renouvelable saone-et-loire photovoltaïque" => ["Energie"],
      "police" => ["Police"],
      "police nationale journee securite routiere moto" => ["Sécurité routière", "Police"],
      "polynésie" => ["Outre-mer"],
      "pompiers" => ["Pompiers"],
      "populationsdémunies" => ["Action sociale"],
      "porcin" => ["Animaux"],
      "posidonie" => ["Biodiversité"],
      "post-bac" => ["Supérieur"],
      "post-permis" => ["Permis"],
      "ppri" => ["Risques majeurs"],
      "pprs menton concertation" => ["Risques majeurs"],
      "pprs saint-laurent-du-var concertation" => ["Risques majeurs"],
      "pref92" => ["Préfecture"],
      "pref971-fipd2024" => ["Prévention"],
      "prefecture" => ["Préfecture"],
      "premiersecoursmotards" => ["Sécurité routière"],
      "prep'ira" => ["Concours"],
      "preparation militaire" => ["Défense"],
      "prevention" => ["Prévention"],
      "primedactivité" => ["Aide financière"],
      "primo-arrivant" => ["Étrangers"],
      "primo-arrivants" => ["Étrangers"],
      "professeur" => ["Enseignant"],
      "professionels de santé" => ["Professionels de santé"],
      "professionelsanté" => ["Professionels de santé"],
      "professionnalisation" => ["Formation"],
      "professionnels de santé" => ["Professionels de santé"],
      "projet alimentaire territorial" => ["Alimentation"],
      "projetdesoincoordonnée" => ["Santé"],
      "promotion-de-la-santé" => ["Santé", "Prévention"],
      "promotion-prévention-de-la-santé" => ["Santé", "Prévention"],
      "protection subsidiaire" => ["Étrangers"],
      "protection-de-l'enfance" => ["Action sociale"],
      "protectionenfance" => ["Action sociale"],
      "précarité" => ["Action sociale"],
      "précarité-menstruelle" => ["Action sociale"],
      "prédation" => ["Animaux"],
      "préfecture" => ["Préfecture"],
      "préfecture92" => ["Préfecture"],
      "prépa talents" => ["Concours"],
      "prépas" => ["Supérieur"],
      "prévention" => ["Prévention"],
      "prévention de la délinquance" => ["Sécurité"],
      "psychologue" => ["Professionels de santé"],
      "psychothérapeute" => ["Professionels de santé"],
      "psychothérapeutes" => ["Professionels de santé"],
      "pédagogie" => ["Education"],
      "pédagogie animations environnement biodiversité eau énergie déchets transition écologique" => ["Environnement", "Transition écologique", "Biodiversité"],
      "pédagogique" => ["Education"],
      "péri-scolaire" => ["Scolaire"],
      "périnatalité" => ["Santé", "Petite enfance"],
      "qualité_air" => ["Environnement"],
      "quatrième" => ["Collège"],
      "qvct" => ["Travail"],
      "qvt" => ["Travail"],
      "radars collectivités loi 3ds sécurité routière" => ["Sécurité routière", "Collectivé territoriale"],
      "radicalisation" => ["Prévention"],
      "radio" => ["Audiovisuel"],
      "rapo etias" => ["Étrangers"],
      "rassemblement" => ["Manifestation"],
      "rassemblements" => ["Manifestation"],
      "recensement dgf voirie 2025" => ["Collectivé territoriale"],
      "recherche sur personnes humaines" => ["Santé"],
      "reclassement" => ["Rh"],
      "recrutement" => ["Recrutement"],
      "rectorat" => ["Education"],
      "refus etias" => ["Étrangers"],
      "reinscription" => ["Inscription"],
      "relevés de notes" => ["Diplôme"],
      "remboursement partiel titres transports" => ["Transport"],
      "renard" => ["Animaux"],
      "repreuplement" => ["Animaux"],
      "ressources humaines" => ["Rh"],
      "ressourceshumaines" => ["Rh"],
      "rgaa" => ["Numérique"],
      "rh" => ["Rh"],
      "rh _école de gendarmerie" => ["Rh"],
      "risque majeur" => ["Risques majeurs"],
      "risques naturels" => ["Risques majeurs"],
      "rivière" => ["Eau"],
      "routier" => ["Transport"],
      "rpg" => ["Agriculture"],
      "rsa" => ["Action sociale"],
      "rssi" => ["Numérique"],
      "rugby" => ["Sport"],
      "réductioninégalitéssocialesanté" => ["Santé"],
      "réfugié" => ["Étrangers"],
      "réfugiés" => ["Étrangers"],
      "régularisation plan d'eau" => ["Eau"],
      "réinscription" => ["Inscription"],
      "rénovation thermique" => ["Energie"],
      "réseaux sociaux" => ["Numérique"],
      "salaires" => ["Travail"],
      "salarié" => ["Travail"],
      "salons" => ["Manifestation"],
      "salubrité" => ["Hygiène"],
      "sanglier" => ["Animaux"],
      "sante" => ["Santé"],
      "santé" => ["Santé"],
      "santémentale" => ["Santé"],
      "santésexuelle" => ["Santé"],
      "sapeur-pompier" => ["Pompiers"],
      "sapeurs-pompiers" => ["Pompiers"],
      "scolaire" => ["Scolaire"],
      "scolarisation" => ["Scolaire"],
      "scolaritã©" => ["Scolaire"],
      "scolarité" => ["Scolaire"],
      "sdis" => ["SDIS"],
      "sdis 86" => ["SDIS"],
      "sdis35" => ["SDIS"],
      "sdis87" => ["SDIS"],
      "securité routière" => ["Sécurité routière"],
      "sedentarite" => ["Santé"],
      "segpa" => ["Collège"],
      "semaine développement durable" => ["Environnement"],
      "semence" => ["Agriculture"],
      "service civique" => ["Service civique"],
      "servicecivique" => ["Service civique"],
      "services d'intermédiation de données" => ["Numérique"],
      "sgar" => ["Préfecture"],
      "sgcd92" => ["Préfecture"],
      "sigave" => ["Outre-mer"],
      "sinp" => ["Biodiversité"],
      "snu" => ["Enfance et jeunesse"],
      "soin" => ["Santé"],
      "soins" => ["Santé"],
      "solaire" => ["Energie"],
      "solutions fondées sur la nature" => ["Environnement"],
      "sortie pédagogique" => ["Scolaire"],
      "sortie scolaire" => ["Scolaire"],
      "souffrancepsychosociale" => ["Santé"],
      "sourds" => ["Handicap"],
      "sous-prefecture" => ["Préfecture"],
      "sousmaindejustice" => ["Justice"],
      "spectacle" => ["Culture"],
      "spectacles" => ["Culture"],
      "sport" => ["Sport"],
      "sport&culture" => ["Culture", "Sport"],
      "sports" => ["Sport"],
      "sportsanté" => ["Santé", "Sport"],
      "spv" => ["Pompiers"],
      "srias" => ["Action sociale"],
      "ssiad" => ["Santé"],
      "sslia" => ["Pompiers"],
      "stage audioprothésiste mesures compensatoires diplôme étranger" => ["Professionels de santé", "Autorisation d'exercer"],
      "startup" => ["innovation"],
      "stav" => ["Lycée"],
      "substances per- et polyfluoroalkylées" => ["Environnement"],
      "substancespsychoactives" => ["Santé"],
      "subvention" => ["Subvention"],
      "subvention de thèse" => ["Subvention"],
      "subventions" => ["Subvention"],
      "supérieur" => ["Supérieur"],
      "suvention" => ["Subvention"],
      "svhc" => ["Environnement"],
      "syndromescollectifsinexpliqués" => ["Santé"],
      "syplo" => ["Logement"],
      "système d'information" => ["Numérique"],
      "sécurisation des organisations" => ["Sécurité"],
      "sécurité" => ["Sécurité"],
      "sécurité numérique et lutte contre la fraude" => ["Numérique", "Sécurité"],
      "sécurité privée" => ["Sécurité"],
      "sécurité routière" => ["Sécurité routière"],
      "sécurité sociale" => ["Sécurité sociale"],
      "ségur" => ["Santé"],
      "ségur numérique" => ["Santé", "Numérique"],
      "séjour" => ["Séjour"],
      "séjours" => ["Séjour"],
      "sûreté" => ["Sécurité"],
      "t3p" => ["Taxi", "Transport"],
      "taupe" => ["Animaux"],
      "taupes" => ["Animaux"],
      "taxe d'apprentissage" => ["Formation"],
      "taxes" => ["Fiscalité"],
      "taxi" => ["Taxi"],
      "taxis" => ["Taxi"],
      "teletravail" => ["Télétravail"],
      "tempete" => ["Risques majeurs"],
      "temps-partiel" => ["Rh"],
      "tempêtes" => ["Risques majeurs"],
      "terminale" => ["Lycée"],
      "terminalegt" => ["Lycée"],
      "tgv" => ["Transport"],
      "tir" => ["Tirs"],
      "tirs" => ["Tirs"],
      "titre professionnel" => ["Diplôme"],
      "tnd" => ["Handicap"],
      "tourisme" => ["Tourisme"],
      "tournage" => ["Cinéma"],
      "train" => ["Transport"],
      "trait de côte" => ["Environnement"],
      "transition écologique" => ["Transition écologique"],
      "transport" => ["Transport"],
      "transport sanitaire" => ["Transport", "Santé"],
      "transports" => ["Transport"],
      "transports de fonds" => ["Sécurité"],
      "travail" => ["Travail"],
      "travailleurs" => ["Travail"],
      "tribunal" => ["Justice"],
      "tva" => ["Fiscalité"],
      "tznr" => ["Action sociale"],
      "télémédecine" => ["Santé"],
      "télésanté" => ["Santé", "Numérique"],
      "télétravail" => ["Télétravail"],
      "udap" => ["Patrimoine"],
      "ueea" => ["Ecoles", "Handicap"],
      "uema" => ["Handicap", "Scolaire"],
      "ulm" => ["Transport"],
      "université" => ["Université"],
      "urbanisme" => ["Urbanisme"],
      "urssaf" => ["Sécurité sociale"],
      "urssaf artistes auteurs" => ["Sécurité sociale"],
      "uvea" => ["Outre-mer"],
      "vacances apprenantes" => ["Education", "Enfance et jeunesse"],
      "vaccination" => ["Santé"],
      "vae" => ["Diplôme", "Formation"],
      "veepap" => ["Supérieur"],
      "vendée globe" => ["Sport"],
      "vidange" => ["Eau"],
      "vidangeur" => ["Eau"],
      "vide-grenier" => ["Manifestation"],
      "videoprotection" => ["Sécurité"],
      "vidéoprotection" => ["Sécurité"],
      "vieassociative" => ["Association"],
      "violences intra-familiales" => ["Famille"],
      "violences urbaines" => ["Sécurité"],
      "visa" => ["Étrangers"],
      "viticulture" => ["Agriculture"],
      "vmdtr" => ["Taxi"],
      "volailles" => ["Animaux", "Agriculture"],
      "vote" => ["Elections"],
      "voyages scolaires" => ["Scolaire"],
      "vtc" => ["Transport"],
      "wallis" => ["Outre-mer"],
      "âgées" => ["Personnes âgées"],
      "école" => ["Ecoles"],
      "écoles" => ["Ecoles"],
      "écologie" => ["Environnement"],
      "économie circulaire" => ["Environnement"],
      "écoresponsable" => ["Transition écologique"],
      "éducatif" => ["Education"],
      "éducation" => ["Education"],
      "éducation populaire" => ["Education", "Enfance et jeunesse"],
      "élection" => ["Elections"],
      "élections" => ["Elections"],
      "électricité" => ["Energie"],
      "élevage" => ["Agriculture", "Animaux"],
      "élèves" => ["Scolaire"],
      "élévation du niveau marin" => ["Environnement"],
      "énergie" => ["Energie"],
      "énergies renouvelables" => ["Energie"],
      "éolien" => ["Energie"],
      "épandage" => ["Agriculture"],
      "équin" => ["Animaux"],
      "érosion" => ["Environnement"],
      "établissement de conduite" => ["Auto-école"],
      "étang" => ["Eau"],
      "étourneau" => ["Animaux"],
      "étrangers" => ["Étrangers"],
      "étude d'impact" => ["Environnement"],
      "étudiant" => ["Supérieur"],
      "étudiants" => ["Supérieur"],
    }.freeze

    def collection
      Procedure.with_discarded.where(LEGACY_TAGS_PRESENT).select(:id, :created_at, "procedures.tags AS legacy_tags")
    end

    def process(procedure)
      names = procedure.legacy_tags.flat_map { MAPPING.fetch(it.strip.downcase, []) }.uniq
      names -= linked_by_create_procedure_tags_task(procedure)

      tags = names.filter_map { procedure_tag(it) }
      procedure.procedure_tags << (tags - procedure.procedure_tags)
    end

    def count
      Procedure.with_discarded.where(LEGACY_TAGS_PRESENT).count
    end

    private

    # CreateProcedureTagsTask a rattaché ces tags aux démarches qui existaient quand elle a tourné :
    # s'il en manque un aujourd'hui, un administrateur l'a probablement retiré, on ne le remet pas.
    # Les démarches créées depuis, des clones pour la plupart, n'en ont pas hérité.
    # Une démarche alors supprimée, qu'elle n'a pas vue, est traitée de même par prudence.
    def linked_by_create_procedure_tags_task(procedure)
      ran_at = create_procedure_tags_task_ran_at
      return [] if ran_at.nil? || procedure.created_at > ran_at

      legacy_values = procedure.legacy_tags.map(&:downcase)
      TAGS_LINKED_BY_CREATE_PROCEDURE_TAGS_TASK.filter { it.downcase.in?(legacy_values) }
    end

    # Elle tournait au premier déploiement, à une date propre à chaque instance ;
    # nil sur une instance qui ne l'a jamais jouée.
    def create_procedure_tags_task_ran_at
      return @create_procedure_tags_task_ran_at if defined?(@create_procedure_tags_task_ran_at)

      @create_procedure_tags_task_ran_at = MaintenanceTasks::Run
        .where(task_name: "Maintenance::CreateProcedureTagsTask", status: :succeeded)
        .minimum(:started_at)
    end

    def procedure_tag(name)
      procedure_tags_by_name[name.downcase] ||= (ProcedureTag.create!(name:) if name.in?(NEW_TAGS))
    end

    def procedure_tags_by_name
      @procedure_tags_by_name ||= ProcedureTag.all.index_by { it.name.downcase }
    end
  end
end
