# frozen_string_literal: true

class Champs::CarteChamp < ChampData
  # Default map location. Center of the World, ahm, France...
  DEFAULT_LON = 2.428462
  DEFAULT_LAT = 46.538192

  # Properties kept from the tile a parcelle was picked on. Its id comes as
  # `cid`, like in #to_feature_collection: `id` is the id of the feature.
  PARCELLE_PROPERTIES = ['arpente', 'commune', 'contenance', 'created', 'numero', 'prefixe', 'section', 'updated'].freeze
  SELECTION_PROPERTIES = ['filename'].freeze
  UUID_FORMAT = /\A\h{8}-\h{4}-\h{4}-\h{4}-\h{12}\z/

  # The editor sends the whole feature collection as the value of the champ.
  # It is not stored: the geo areas are synced with it by feature id.
  #
  # - a feature with an unknown id becomes a new geo area (the editor
  #   generates the uuids);
  # - a known one updates its description, and its geometry when the usager
  #   drew it: the geometry of a parcelle comes from the cadastre, not from
  #   the tile the usager clicked on (see FetchCadastreRealGeometryJob);
  # - a geo area missing from the collection is destroyed.
  #
  # A feature with an invalid geometry is left out, and the rest is saved: an
  # imported file in the wrong projection must not block every later save.
  # The editor learns which ones from #rejected_features, and drops them.
  #
  # nil or blank (a clone, a reset on type change) leaves the geo areas alone.
  def value=(value)
    @rejected_features = {}
    features = parse_features(value)
    sync_geo_areas(features) if features
  end

  # The error messages of the geometries the last value= left out, by feature
  # id. Only known to the champ that was assigned the value.
  def rejected_features
    @rejected_features || {}
  end

  def legend_label?
    true
  end

  def html_label?
    false
  end

  # We are not using scopes here as we want to access
  # the following collections on unsaved records.
  def cadastres
    if cadastres?
      geo_areas.filter(&:cadastre?)
    else
      []
    end
  end

  def rpgs
    if rpg?
      geo_areas.filter(&:rpg?)
    else
      []
    end
  end

  def selections_utilisateur
    geo_areas.filter do |area|
      area.source == GeoArea.sources.fetch(:selection_utilisateur)
    end
  end

  def cadastres?
    type_de_champ.layer_enabled?(:cadastres)
  end

  def rpg?
    type_de_champ.layer_enabled?(:rpg)
  end

  def optional_layers
    type_de_champ.carte_optional_layers
  end

  def render_options
    { layers: optional_layers }
  end

  def position
    if dossier.present?
      dossier.geo_position
    else
      lon = DEFAULT_LON.to_s
      lat = DEFAULT_LAT.to_s
      zoom = "13"

      { lon: lon, lat: lat, zoom: zoom }
    end
  end

  def bounding_box
    if geo_areas.present?
      GeojsonService.bbox(type: 'FeatureCollection', features: geo_areas.map(&:to_feature))
    elsif dossier.present?
      point = dossier.geo_position
      GeojsonService.bbox(type: 'Feature', geometry: { type: 'Point', coordinates: [point[:lon], point[:lat]] })
    else
      GeojsonService.bbox(type: 'Feature', geometry: { type: 'Point', coordinates: [DEFAULT_LON, DEFAULT_LAT] })
    end
  end

  def to_feature_collection
    {
      type: 'FeatureCollection',
      id: stable_id,
      bbox: bounding_box,
      features: geo_areas.map(&:to_feature),
    }
  end

  def geometry?
    geo_areas.present?
  end

  # --- Static render ---------------------------------------------------------
  #
  # The image lives in its own `static_map` attachment rather than in
  # `piece_justificative_file`. It is not a pièce jointe: the usager did not
  # supply it, we generated it, and it exists only to be printed in the PDF
  # export. Keeping it under a separate name is what keeps it out of the pj
  # exports, the instructeur gallery, the watermarking and the auto-purge —
  # all of which walk `piece_justificative_file`.

  STATIC_MAP_FILENAME = 'carte.jpg'
  STATIC_MAP_CONTENT_TYPE = 'image/jpeg'
  STATIC_MAP_DIGEST_KEY = 'static_map_digest'

  # `static_map` is the ActiveStorage::Attached::One generated by
  # has_one_attached on ChampData; callers use `static_map.attached?`.

  def static_map_up_to_date?(digest)
    static_map.blob&.metadata&.dig(STATIC_MAP_DIGEST_KEY) == digest
  end

  def attach_static_map(io, digest:)
    blob = ActiveStorage::Blob.create_and_upload!(
      io:,
      filename: STATIC_MAP_FILENAME,
      content_type: STATIC_MAP_CONTENT_TYPE,
      # The image comes from us: running it through the virus scanner and the
      # blob processor would be pointless. `processed` short-circuits
      # AttachmentProcessorConcern.
      metadata: { 'processed' => true, 'virus_scan_result' => ActiveStorage::VirusScanner::SAFE, STATIC_MAP_DIGEST_KEY => digest }
    )

    # has_one_attached replaces on attach, so a re-render cannot pile up
    # attachments nor leave the champ imageless in between.
    static_map.attach(blob)
  end

  def purge_static_map
    static_map.purge if static_map.attached?
  end

  def selection_utilisateur_legacy_geo_area
    geometry = selection_utilisateur_legacy_geometry
    if geometry.present?
      GeoArea.new(
        source: GeoArea.sources.fetch(:selection_utilisateur),
        geometry: geometry
      )
    end
  end

  private

  def parse_features(value)
    return if value.blank?

    feature_collection = JSON.parse(value)
    features = feature_collection['features'] if feature_collection.is_a?(Hash)
    return if !features.is_a?(Array)

    features
      .filter { it.is_a?(Hash) && it['id'].present? && it['geometry'].is_a?(Hash) && it['geometry'].present? }
      .index_by { it['id'].to_s }
  rescue JSON::ParserError
    nil
  end

  def sync_geo_areas(features)
    geo_areas.each do |geo_area|
      feature = features.delete(geo_area.uuid)

      if feature.nil?
        geo_area.mark_for_destruction
      else
        update_geo_area(geo_area, feature)
      end
    end

    features.each { |id, feature| build_geo_area(id, feature) }
  end

  def update_geo_area(geo_area, feature)
    if geo_area.selection_utilisateur? && geometry_valid?(geo_area.uuid, feature['geometry'])
      geo_area.geometry = feature['geometry']
    end

    description = feature_properties(feature)['description'].presence
    if description != geo_area.description
      geo_area.properties = geo_area.properties.merge('description' => description)
    end
  end

  def build_geo_area(id, feature)
    return if !id.match?(UUID_FORMAT)
    return if !geometry_valid?(id, feature['geometry'])

    properties = feature_properties(feature)
    source = properties['source'].presence_in(GeoArea.sources.values) || GeoArea.sources.fetch(:selection_utilisateur)
    kept_properties = if source == GeoArea.sources.fetch(:selection_utilisateur)
      properties.slice('description', *SELECTION_PROPERTIES)
    else
      return if parcelle_selected?(source, properties['cid'])

      properties.slice('description', *PARCELLE_PROPERTIES).merge('id' => properties['cid'])
    end

    geo_areas.build(
      uuid: id,
      source:,
      geometry: feature['geometry'],
      properties: kept_properties.compact_blank
    )
  end

  def geometry_valid?(id, geometry)
    errors = GeoArea.new(geometry:).tap(&:validate).errors.where(:geometry)
    @rejected_features[id] = errors.map(&:message) if errors.any?
    errors.none?
  end

  def feature_properties(feature)
    properties = feature['properties']
    properties.is_a?(Hash) ? properties : {}
  end

  # A parcelle is picked once, whatever the collection says.
  def parcelle_selected?(source, cid)
    cid.blank? || geo_areas.any? { it.source == source && !it.marked_for_destruction? && it.cid == cid }
  end

  def selection_utilisateur_legacy_geometry
    if selections_utilisateur.present?
      {
        type: 'MultiPolygon',
        coordinates: selections_utilisateur.filter do |selection_utilisateur|
          selection_utilisateur.geometry['type'] == 'Polygon'
        end.map do |selection_utilisateur|
          selection_utilisateur.geometry['coordinates']
        end,
      }
    else
      nil
    end
  end
end
